/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EXIFDataBundle */

#ifndef _Included_EXIFDataBundle
#define _Included_EXIFDataBundle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EXIFDataBundle
 * Method:    getDateTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getDateTime
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getMaker
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getMaker
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getDeviceModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getDeviceModel
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getExposureTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getExposureTime
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getISOSpeed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getISOSpeed
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getWhiteBalance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getWhiteBalance
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getXDimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getXDimension
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getYDimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getYDimension
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getXResolution
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getXResolution
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getYResolution
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getYResolution
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getLongitude
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getLongitude
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getLatitude
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getLatitude
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    getAltitude
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getAltitude
  (JNIEnv *, jobject);

/*
 * Class:     EXIFDataBundle
 * Method:    isStitchedPicture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_madv360_exiv2_EXIFDataBundle_isStitchedPicture
  (JNIEnv *, jobject);


JNIEXPORT jstring JNICALL Java_com_madv360_exiv2_EXIFDataBundle_getExposureBiasValue(JNIEnv *env, jobject self);

/*
 * Class:     EXIFDataBundle
 * Method:    createNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_madv360_exiv2_EXIFDataBundle_createNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     EXIFDataBundle
 * Method:    releaseNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_madv360_exiv2_EXIFDataBundle_releaseNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
