#source 'qiudong@172.172.172.10:/data/gitdb/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

def shared_pods

pod 'AFNetworking', '~> 2.5.4'
#pod 'SSZipArchive', '~> 0.2.2'
#pod 'SDWebImage', '~> 3.7.2'
##pod 'MJExtension', '3.0.3'
#pod 'JLRoutes', '~> 1.5.2'
#pod 'SSKeychain', '~> 1.2.3'

#vendor
#pod 'EaseMobSDKFull', '~> 2.1.7'
#pod "Qiniu", "~> 7.0"

#own
#pod 'Realm', '~> 0.92.30'
#pod 'WCategories', '~> 0.0.2'
#pod 'WUtilities', '~> 0.0.3'
#pod 'WEmoji', '~> 0.0.1'

#views
#pod 'THProgressView', '~> 1.0'
#pod 'RBBAnimation', '~> 0.4.0'
#pod 'SCLAlertView-Objective-C', '~> 0.7.3'
##pod 'SVPullToRefresh', '~> 0.4.1'

#controllers
#pod 'ECSlidingViewController', '~> 2.0.3'
#pod 'MWPhotoBrowser', '~> 1.4.1'

#pod 'Masonry'

#pod 'MJRefresh', '3.1.12'
pod 'Realm', '2.8.3'
end

target 'MADVCamera' do
    shared_pods
end
